zf_admin_duty_index:
    path:     /
    defaults: { _controller: "ZtrintFinanceAdminBundle:Duty:index" }
    methods:  GET

zf_admin_duty_show:
    path:     /{id}/show
    defaults: { _controller: "ZtrintFinanceAdminBundle:Duty:show" }
    methods:  GET

zf_admin_duty_new:
    path:     /new
    defaults: { _controller: "ZtrintFinanceAdminBundle:Duty:new" }
    methods:  [GET, POST]

zf_admin_duty_edit:
    path:     /{id}/edit
    defaults: { _controller: "ZtrintFinanceAdminBundle:Duty:edit" }
    methods:  [GET, POST]

zf_admin_duty_delete:
    path:     /{id}/delete
    defaults: { _controller: "ZtrintFinanceAdminBundle:Duty:delete" }
    methods:  DELETE
