zf_admin_portfolio_index:
    path:     /
    defaults: { _controller: "ZtrintFinanceAdminBundle:Portfolio:index" }
    methods:  GET

zf_admin_portfolio_show:
    path:     /{id}/show
    defaults: { _controller: "ZtrintFinanceAdminBundle:Portfolio:show" }
    methods:  GET

zf_admin_portfolio_new:
    path:     /new
    defaults: { _controller: "ZtrintFinanceAdminBundle:Portfolio:new" }
    methods:  [GET, POST]

zf_admin_portfolio_edit:
    path:     /{id}/edit
    defaults: { _controller: "ZtrintFinanceAdminBundle:Portfolio:edit" }
    methods:  [GET, POST]

zf_admin_portfolio_delete:
    path:     /{id}/delete
    defaults: { _controller: "ZtrintFinanceAdminBundle:Portfolio:delete" }
    methods:  DELETE
