Ztrint\Finance\AdminBundle\Entity\Cashgroup:
    type: entity
    table: cashgroup
    id:
        id:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
            id: true
            generator:
                strategy: NONE
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    oneToMany:
        boxes:
            targetEntity: Cashbox
            mappedBy: cashgroup
            cascade: {  }
            orphanRemoval: false
            orderBy: 
              currency: DESC
    lifecycleCallbacks: {  }
