Ztrint\Finance\AdminBundle\Entity\Currency:
    type: entity
    table: currency
    id:
        id:
            type: string
            nullable: false
            length: 3
            options:
                fixed: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        valuebuy:
            type: decimal
            nullable: false
            precision: 6
            scale: 3
        valuesell:
            type: decimal
            nullable: false
            precision: 6
            scale: 3
        valuesell2:
            type: decimal
            nullable: false
            precision: 6
            scale: 3
    oneToMany:
        boxes:
            targetEntity: Cashbox
            mappedBy: currency
            cascade: {  }
            orphanRemoval: false
            orderBy: 
              name: ASC
    lifecycleCallbacks: {  }
