Ztrint\Finance\AdminBundle\Entity\Io:
    type: entity
    table: io
    indexes:
        at:
            columns:
                - at
        source:
            columns:
                - source
        dest:
            columns:
                - dest
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        at:
            type: date
            nullable: false
        concept:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        amount:
            type: decimal
            nullable: false
            precision: 12
            scale: 3
        price:
            type: decimal
            nullable: false
            precision: 6
            scale: 3
    manyToOne:
        source:
            targetEntity: Cashbox
            cascade: {  }
            fetch: LAZY
            #mappedBy: null
            inversedBy: outcomes
            joinColumns:
                source:
                    referencedColumnName: id
            orphanRemoval: false
        dest:
            targetEntity: Cashbox
            cascade: {  }
            fetch: LAZY
            #mappedBy: null
            inversedBy: incomes
            joinColumns:
                dest:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
