Ztrint\Finance\AdminBundle\Entity\Portfolio:
    type: entity
    table: portfolio
    indexes:
        currency:
            columns:
                - currency
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        start:
            type: date
            nullable: false
        end:
            type: date
            nullable: false
        deposit:
            type: decimal
            nullable: false
            precision: 12
            scale: 3
        anr:
            type: decimal
            nullable: false
            precision: 5
            scale: 3
            options:
                comment: 'tasa nominal anual'
            column: ANR
        cert:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
    manyToOne:
        currency:
            targetEntity: Currency
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                currency:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
